# Generated by Django 2.1.7 on 2019-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='carriers',
            field=models.ManyToManyField(to='trvl.Carrier'),
        ),
    ]
