# Generated by Django 2.1.7 on 2019-03-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trvl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport1', to='trvl.Airport')),
                ('airport2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport2', to='trvl.Airport')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trvl.Carrier')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together={('airport1', 'airport2', 'carrier')},
        ),
    ]
