# Generated by Django 2.1.7 on 2019-03-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trvl', '0002_auto_20190316_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='routes',
            name='airport1',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='airport2',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='carriers',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='delay_count_statistic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.DelayCountStatistics'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='delay_time_statistic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.DelayTimeStatistics'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='flight_statistic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.FlightStatistics'),
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
