# Generated by Django 2.1.7 on 2019-03-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvl', '0003_auto_20190317_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='delay_count_statistic',
            new_name='delay_count',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='delay_time_statistic',
            new_name='delay_time',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='flight_statistic',
            new_name='flight',
        ),
    ]
