# Generated by Django 2.1.7 on 2019-03-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trvl', '0004_auto_20190317_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='trvl.Airport'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='trvl.Carrier'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='delay_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.DelayCountStatistics'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='delay_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.DelayTimeStatistics'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trvl.FlightStatistics'),
        ),
    ]
